# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

require "./support"

module Radarr
  def_string_enum AddMovieMethod, {
    Manual:     "manual",
    List:       "list",
    Collection: "collection",
  }

  def_string_enum ApplyTags, {
    Add:     "add",
    Remove:  "remove",
    Replace: "replace",
  }

  def_string_enum AuthenticationRequiredType, {
    Enabled:                   "enabled",
    DisabledForLocalAddresses: "disabledForLocalAddresses",
  }

  def_string_enum AuthenticationType, {
    None:     "none",
    Basic:    "basic",
    Forms:    "forms",
    External: "external",
  }

  def_string_enum BackupType, {
    Scheduled: "scheduled",
    Manual:    "manual",
    Update:    "update",
  }

  def_string_enum CalendarReleaseType, {
    CinemaRelease:   "cinemaRelease",
    DigitalRelease:  "digitalRelease",
    PhysicalRelease: "physicalRelease",
  }

  def_string_enum CertificateValidationType, {
    Enabled:                   "enabled",
    DisabledForLocalAddresses: "disabledForLocalAddresses",
    Disabled:                  "disabled",
  }

  def_string_enum ColonReplacementFormat, {
    Delete:         "delete",
    Dash:           "dash",
    SpaceDash:      "spaceDash",
    SpaceDashSpace: "spaceDashSpace",
    Smart:          "smart",
  }

  def_string_enum CommandPriority, {
    Normal: "normal",
    High:   "high",
    Low:    "low",
  }

  def_string_enum CommandResult, {
    Unknown:      "unknown",
    Successful:   "successful",
    Unsuccessful: "unsuccessful",
  }

  def_string_enum CommandStatus, {
    Queued:    "queued",
    Started:   "started",
    Completed: "completed",
    Failed:    "failed",
    Aborted:   "aborted",
    Cancelled: "cancelled",
    Orphaned:  "orphaned",
  }

  def_string_enum CommandTrigger, {
    Unspecified: "unspecified",
    Manual:      "manual",
    Scheduled:   "scheduled",
  }

  def_string_enum CreditType, {
    Cast: "cast",
    Crew: "crew",
  }

  def_string_enum DatabaseType, {
    SqLite:     "sqLite",
    PostgreSQL: "postgreSQL",
  }

  def_string_enum DownloadProtocol, {
    Unknown: "unknown",
    Usenet:  "usenet",
    Torrent: "torrent",
  }

  def_string_enum ExtraFileType, {
    Subtitle: "subtitle",
    Metadata: "metadata",
    Other:    "other",
  }

  def_string_enum FileDateType, {
    None:    "none",
    Cinemas: "cinemas",
    Release: "release",
  }

  def_string_enum HealthCheckResult, {
    Ok:      "ok",
    Notice:  "notice",
    Warning: "warning",
    Error:   "error",
  }

  def_string_enum ImportListType, {
    Program:  "program",
    Tmdb:     "tmdb",
    Trakt:    "trakt",
    Plex:     "plex",
    Simkl:    "simkl",
    Other:    "other",
    Advanced: "advanced",
  }

  def_string_enum MediaCoverTypes, {
    Unknown:    "unknown",
    Poster:     "poster",
    Banner:     "banner",
    Fanart:     "fanart",
    Screenshot: "screenshot",
    Headshot:   "headshot",
    Clearlogo:  "clearlogo",
  }

  def_string_enum Modifier, {
    None:     "none",
    Regional: "regional",
    Screener: "screener",
    Rawhd:    "rawhd",
    Brdisk:   "brdisk",
    Remux:    "remux",
  }

  def_string_enum MonitorTypes, {
    MovieOnly:          "movieOnly",
    MovieAndCollection: "movieAndCollection",
    None:               "none",
  }

  def_string_enum MovieHistoryEventType, {
    Unknown:                "unknown",
    Grabbed:                "grabbed",
    DownloadFolderImported: "downloadFolderImported",
    DownloadFailed:         "downloadFailed",
    MovieFileDeleted:       "movieFileDeleted",
    MovieFolderImported:    "movieFolderImported",
    MovieFileRenamed:       "movieFileRenamed",
    DownloadIgnored:        "downloadIgnored",
  }

  def_string_enum MovieRuntimeFormatType, {
    HoursMinutes: "hoursMinutes",
    Minutes:      "minutes",
  }

  def_string_enum MovieStatusType, {
    Tba:       "tba",
    Announced: "announced",
    InCinemas: "inCinemas",
    Released:  "released",
    Deleted:   "deleted",
  }

  def_string_enum PrivacyLevel, {
    Normal:   "normal",
    Password: "password",
    ApiKey:   "apiKey",
    UserName: "userName",
  }

  def_string_enum ProperDownloadTypes, {
    PreferAndUpgrade: "preferAndUpgrade",
    DoNotUpgrade:     "doNotUpgrade",
    DoNotPrefer:      "doNotPrefer",
  }

  def_string_enum ProviderMessageType, {
    Info:    "info",
    Warning: "warning",
    Error:   "error",
  }

  def_string_enum ProxyType, {
    Http:   "http",
    Socks4: "socks4",
    Socks5: "socks5",
  }

  def_string_enum QualitySource, {
    Unknown:   "unknown",
    Cam:       "cam",
    Telesync:  "telesync",
    Telecine:  "telecine",
    Workprint: "workprint",
    Dvd:       "dvd",
    Tv:        "tv",
    Webdl:     "webdl",
    Webrip:    "webrip",
    Bluray:    "bluray",
  }

  def_string_enum QueueStatus, {
    Unknown:                   "unknown",
    Queued:                    "queued",
    Paused:                    "paused",
    Downloading:               "downloading",
    Completed:                 "completed",
    Failed:                    "failed",
    Warning:                   "warning",
    Delay:                     "delay",
    DownloadClientUnavailable: "downloadClientUnavailable",
    Fallback:                  "fallback",
  }

  def_string_enum RatingType, {
    User:   "user",
    Critic: "critic",
  }

  def_string_enum RejectionType, {
    Permanent: "permanent",
    Temporary: "temporary",
  }

  def_string_enum RescanAfterRefreshType, {
    Always:      "always",
    AfterManual: "afterManual",
    Never:       "never",
  }

  def_string_enum RuntimeMode, {
    Console: "console",
    Service: "service",
    Tray:    "tray",
  }

  def_string_enum SortDirection, {
    Default:    "default",
    Ascending:  "ascending",
    Descending: "descending",
  }

  def_string_enum SourceType, {
    Tmdb:     "tmdb",
    Mappings: "mappings",
    User:     "user",
    Indexer:  "indexer",
  }

  def_string_enum TMDbCountryCode, {
    Au: "au",
    Br: "br",
    Ca: "ca",
    Fr: "fr",
    De: "de",
    Gb: "gb",
    In: "in",
    Ie: "ie",
    It: "it",
    Nz: "nz",
    Ro: "ro",
    Es: "es",
    Us: "us",
  }

  def_string_enum TrackedDownloadState, {
    Downloading:   "downloading",
    ImportBlocked: "importBlocked",
    ImportPending: "importPending",
    Importing:     "importing",
    Imported:      "imported",
    FailedPending: "failedPending",
    Failed:        "failed",
    Ignored:       "ignored",
  }

  def_string_enum TrackedDownloadStatus, {
    Ok:      "ok",
    Warning: "warning",
    Error:   "error",
  }

  def_string_enum UpdateMechanism, {
    BuiltIn:  "builtIn",
    Script:   "script",
    External: "external",
    Apt:      "apt",
    Docker:   "docker",
  }
end
