# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::AlternativeTitle
  def initialize(@client : Radarr::Client)
  end

  def list(movie_id : Int32? = nil, movie_metadata_id : Int32? = nil) : Array(Radarr::Model::AlternativeTitleResource)
    query = Radarr::Query.new
    query.add("movieId", movie_id)
    query.add("movieMetadataId", movie_metadata_id)
    @client.request_many(:get, "/api/v3/alttitle", Radarr::Model::AlternativeTitleResource, query)
  end

  def get(id : Int32) : Radarr::Model::AlternativeTitleResource?
    @client.request_one(:get, "/api/v3/alttitle/#{id}", Radarr::Model::AlternativeTitleResource)
  end
end
