# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::ApiInfo
  def initialize(@client : Radarr::Client)
  end

  def list : Radarr::Model::ApiInfoResource?
    @client.request_one(:get, "/api", Radarr::Model::ApiInfoResource)
  end
end
