# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Authentication
  def initialize(@client : Radarr::Client)
  end

  def list : Nil
    @client.request(:get, "/logout")
  end
end
