# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::AutoTagging
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::AutoTaggingResource)
    @client.request_many(:get, "/api/v3/autotagging", Radarr::Model::AutoTaggingResource)
  end

  def create(body : Radarr::Model::AutoTaggingResource) : Radarr::Model::AutoTaggingResource?
    @client.request_one(:post, "/api/v3/autotagging", Radarr::Model::AutoTaggingResource, nil, body)
  end

  def list_schema : Nil
    @client.request(:get, "/api/v3/autotagging/schema")
  end

  def get(id : Int32) : Radarr::Model::AutoTaggingResource?
    @client.request_one(:get, "/api/v3/autotagging/#{id}", Radarr::Model::AutoTaggingResource)
  end

  def update(id : Int32, body : Radarr::Model::AutoTaggingResource) : Radarr::Model::AutoTaggingResource?
    @client.request_one(:put, "/api/v3/autotagging/#{id}", Radarr::Model::AutoTaggingResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/autotagging/#{id}")
  end
end
