# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Backup
  def initialize(@client : Radarr::Client)
  end

  def list_backup : Array(Radarr::Model::BackupResource)
    @client.request_many(:get, "/api/v3/system/backup", Radarr::Model::BackupResource)
  end

  def create_backup_restore_upload : Nil
    @client.request(:post, "/api/v3/system/backup/restore/upload")
  end

  def create_backup_restore(id : Int32) : Nil
    @client.request(:post, "/api/v3/system/backup/restore/#{id}")
  end

  def delete_backup(id : Int32) : Nil
    @client.request(:delete, "/api/v3/system/backup/#{id}")
  end
end
