# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Blocklist
  def initialize(@client : Radarr::Client)
  end

  def list(page : Int32? = nil, page_size : Int32? = nil, sort_key : String? = nil, sort_direction : Radarr::SortDirection? = nil, movie_ids : Array(Int32)? = nil, protocols : Array(Radarr::DownloadProtocol)? = nil) : Radarr::Model::BlocklistResourcePagingResource?
    query = Radarr::Query.new
    query.add("page", page)
    query.add("pageSize", page_size)
    query.add("sortKey", sort_key)
    query.add("sortDirection", sort_direction)
    query.add("movieIds", movie_ids)
    query.add("protocols", protocols)
    @client.request_one(:get, "/api/v3/blocklist", Radarr::Model::BlocklistResourcePagingResource, query)
  end

  def delete_bulk(body : Radarr::Model::BlocklistBulkResource) : Nil
    @client.request(:delete, "/api/v3/blocklist/bulk", nil, body)
  end

  def list_movie(movie_id : Int32? = nil) : Array(Radarr::Model::BlocklistResource)
    query = Radarr::Query.new
    query.add("movieId", movie_id)
    @client.request_many(:get, "/api/v3/blocklist/movie", Radarr::Model::BlocklistResource, query)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/blocklist/#{id}")
  end
end
