# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Calendar
  def initialize(@client : Radarr::Client)
  end

  def list(start : Time? = nil, end_field : Time? = nil, unmonitored : Bool? = nil, tags : String? = nil) : Array(Radarr::Model::MovieResource)
    query = Radarr::Query.new
    query.add("start", start)
    query.add("end", end_field)
    query.add("unmonitored", unmonitored)
    query.add("tags", tags)
    @client.request_many(:get, "/api/v3/calendar", Radarr::Model::MovieResource, query)
  end
end
