# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Collection
  def initialize(@client : Radarr::Client)
  end

  def list(tmdb_id : Int32? = nil) : Array(Radarr::Model::CollectionResource)
    query = Radarr::Query.new
    query.add("tmdbId", tmdb_id)
    @client.request_many(:get, "/api/v3/collection", Radarr::Model::CollectionResource, query)
  end

  def update(body : Radarr::Model::CollectionUpdateResource) : Nil
    @client.request(:put, "/api/v3/collection", nil, body)
  end

  def get(id : Int32) : Radarr::Model::CollectionResource?
    @client.request_one(:get, "/api/v3/collection/#{id}", Radarr::Model::CollectionResource)
  end

  def update_2(id : Int32, body : Radarr::Model::CollectionResource) : Radarr::Model::CollectionResource?
    @client.request_one(:put, "/api/v3/collection/#{id}", Radarr::Model::CollectionResource, nil, body)
  end
end
