# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Command
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::CommandResource)
    @client.request_many(:get, "/api/v3/command", Radarr::Model::CommandResource)
  end

  def create(body : Radarr::Model::CommandResource) : Radarr::Model::CommandResource?
    @client.request_one(:post, "/api/v3/command", Radarr::Model::CommandResource, nil, body)
  end

  def get(id : Int32) : Radarr::Model::CommandResource?
    @client.request_one(:get, "/api/v3/command/#{id}", Radarr::Model::CommandResource)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/command/#{id}")
  end
end
