# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Credit
  def initialize(@client : Radarr::Client)
  end

  def list(movie_id : Int32? = nil, movie_metadata_id : Int32? = nil) : Nil
    query = Radarr::Query.new
    query.add("movieId", movie_id)
    query.add("movieMetadataId", movie_metadata_id)
    @client.request(:get, "/api/v3/credit", query)
  end

  def get(id : Int32) : Radarr::Model::CreditResource?
    @client.request_one(:get, "/api/v3/credit/#{id}", Radarr::Model::CreditResource)
  end
end
