# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::CustomFilter
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::CustomFilterResource)
    @client.request_many(:get, "/api/v3/customfilter", Radarr::Model::CustomFilterResource)
  end

  def create(body : Radarr::Model::CustomFilterResource) : Radarr::Model::CustomFilterResource?
    @client.request_one(:post, "/api/v3/customfilter", Radarr::Model::CustomFilterResource, nil, body)
  end

  def get(id : Int32) : Radarr::Model::CustomFilterResource?
    @client.request_one(:get, "/api/v3/customfilter/#{id}", Radarr::Model::CustomFilterResource)
  end

  def update(id : Int32, body : Radarr::Model::CustomFilterResource) : Radarr::Model::CustomFilterResource?
    @client.request_one(:put, "/api/v3/customfilter/#{id}", Radarr::Model::CustomFilterResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/customfilter/#{id}")
  end
end
