# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::CustomFormat
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::CustomFormatResource)
    @client.request_many(:get, "/api/v3/customformat", Radarr::Model::CustomFormatResource)
  end

  def create(body : Radarr::Model::CustomFormatResource) : Radarr::Model::CustomFormatResource?
    @client.request_one(:post, "/api/v3/customformat", Radarr::Model::CustomFormatResource, nil, body)
  end

  def update_bulk(body : Radarr::Model::CustomFormatBulkResource) : Radarr::Model::CustomFormatResource?
    @client.request_one(:put, "/api/v3/customformat/bulk", Radarr::Model::CustomFormatResource, nil, body)
  end

  def delete_bulk(body : Radarr::Model::CustomFormatBulkResource) : Nil
    @client.request(:delete, "/api/v3/customformat/bulk", nil, body)
  end

  def list_schema : Nil
    @client.request(:get, "/api/v3/customformat/schema")
  end

  def get(id : Int32) : Radarr::Model::CustomFormatResource?
    @client.request_one(:get, "/api/v3/customformat/#{id}", Radarr::Model::CustomFormatResource)
  end

  def update(id : Int32, body : Radarr::Model::CustomFormatResource) : Radarr::Model::CustomFormatResource?
    @client.request_one(:put, "/api/v3/customformat/#{id}", Radarr::Model::CustomFormatResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/customformat/#{id}")
  end
end
