# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::DelayProfile
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::DelayProfileResource)
    @client.request_many(:get, "/api/v3/delayprofile", Radarr::Model::DelayProfileResource)
  end

  def create(body : Radarr::Model::DelayProfileResource) : Radarr::Model::DelayProfileResource?
    @client.request_one(:post, "/api/v3/delayprofile", Radarr::Model::DelayProfileResource, nil, body)
  end

  def update_reorder(id : Int32, after : Int32? = nil) : Array(Radarr::Model::DelayProfileResource)
    query = Radarr::Query.new
    query.add("after", after)
    @client.request_many(:put, "/api/v3/delayprofile/reorder/#{id}", Radarr::Model::DelayProfileResource, query)
  end

  def get(id : Int32) : Radarr::Model::DelayProfileResource?
    @client.request_one(:get, "/api/v3/delayprofile/#{id}", Radarr::Model::DelayProfileResource)
  end

  def update(id : Int32, body : Radarr::Model::DelayProfileResource) : Radarr::Model::DelayProfileResource?
    @client.request_one(:put, "/api/v3/delayprofile/#{id}", Radarr::Model::DelayProfileResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/delayprofile/#{id}")
  end
end
