# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::DiskSpace
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::DiskSpaceResource)
    @client.request_many(:get, "/api/v3/diskspace", Radarr::Model::DiskSpaceResource)
  end
end
