# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::DownloadClientConfig
  def initialize(@client : Radarr::Client)
  end

  def list_downloadclient : Radarr::Model::DownloadClientConfigResource?
    @client.request_one(:get, "/api/v3/config/downloadclient", Radarr::Model::DownloadClientConfigResource)
  end

  def get_downloadclient(id : Int32) : Radarr::Model::DownloadClientConfigResource?
    @client.request_one(:get, "/api/v3/config/downloadclient/#{id}", Radarr::Model::DownloadClientConfigResource)
  end

  def update_downloadclient(id : Int32, body : Radarr::Model::DownloadClientConfigResource) : Radarr::Model::DownloadClientConfigResource?
    @client.request_one(:put, "/api/v3/config/downloadclient/#{id}", Radarr::Model::DownloadClientConfigResource, nil, body)
  end
end
