# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::DownloadClient
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::DownloadClientResource)
    @client.request_many(:get, "/api/v3/downloadclient", Radarr::Model::DownloadClientResource)
  end

  def create(body : Radarr::Model::DownloadClientResource, force_save : Bool? = nil) : Radarr::Model::DownloadClientResource?
    query = Radarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:post, "/api/v3/downloadclient", Radarr::Model::DownloadClientResource, query, body)
  end

  def create_action(name : String, body : Radarr::Model::DownloadClientResource) : Nil
    @client.request(:post, "/api/v3/downloadclient/action/#{name}", nil, body)
  end

  def update_bulk(body : Radarr::Model::DownloadClientBulkResource) : Radarr::Model::DownloadClientResource?
    @client.request_one(:put, "/api/v3/downloadclient/bulk", Radarr::Model::DownloadClientResource, nil, body)
  end

  def delete_bulk(body : Radarr::Model::DownloadClientBulkResource) : Nil
    @client.request(:delete, "/api/v3/downloadclient/bulk", nil, body)
  end

  def list_schema : Array(Radarr::Model::DownloadClientResource)
    @client.request_many(:get, "/api/v3/downloadclient/schema", Radarr::Model::DownloadClientResource)
  end

  def create_test(body : Radarr::Model::DownloadClientResource, force_test : Bool? = nil) : Nil
    query = Radarr::Query.new
    query.add("forceTest", force_test)
    @client.request(:post, "/api/v3/downloadclient/test", query, body)
  end

  def create_testall : Nil
    @client.request(:post, "/api/v3/downloadclient/testall")
  end

  def get(id : Int32) : Radarr::Model::DownloadClientResource?
    @client.request_one(:get, "/api/v3/downloadclient/#{id}", Radarr::Model::DownloadClientResource)
  end

  def update(id : Int32, body : Radarr::Model::DownloadClientResource, force_save : Bool? = nil) : Radarr::Model::DownloadClientResource?
    query = Radarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:put, "/api/v3/downloadclient/#{id}", Radarr::Model::DownloadClientResource, query, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/downloadclient/#{id}")
  end
end
