# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::ExtraFile
  def initialize(@client : Radarr::Client)
  end

  def list(movie_id : Int32? = nil) : Array(Radarr::Model::ExtraFileResource)
    query = Radarr::Query.new
    query.add("movieId", movie_id)
    @client.request_many(:get, "/api/v3/extrafile", Radarr::Model::ExtraFileResource, query)
  end
end
