# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Health
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::HealthResource)
    @client.request_many(:get, "/api/v3/health", Radarr::Model::HealthResource)
  end
end
