# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::History
  def initialize(@client : Radarr::Client)
  end

  def list(page : Int32? = nil, page_size : Int32? = nil, sort_key : String? = nil, sort_direction : Radarr::SortDirection? = nil, include_movie : Bool? = nil, event_type : Array(Int32)? = nil, download_id : String? = nil, movie_ids : Array(Int32)? = nil, languages : Array(Int32)? = nil, quality : Array(Int32)? = nil) : Radarr::Model::HistoryResourcePagingResource?
    query = Radarr::Query.new
    query.add("page", page)
    query.add("pageSize", page_size)
    query.add("sortKey", sort_key)
    query.add("sortDirection", sort_direction)
    query.add("includeMovie", include_movie)
    query.add("eventType", event_type)
    query.add("downloadId", download_id)
    query.add("movieIds", movie_ids)
    query.add("languages", languages)
    query.add("quality", quality)
    @client.request_one(:get, "/api/v3/history", Radarr::Model::HistoryResourcePagingResource, query)
  end

  def create_failed(id : Int32) : Nil
    @client.request(:post, "/api/v3/history/failed/#{id}")
  end

  def list_movie(movie_id : Int32? = nil, event_type : Radarr::MovieHistoryEventType? = nil, include_movie : Bool? = nil) : Array(Radarr::Model::HistoryResource)
    query = Radarr::Query.new
    query.add("movieId", movie_id)
    query.add("eventType", event_type)
    query.add("includeMovie", include_movie)
    @client.request_many(:get, "/api/v3/history/movie", Radarr::Model::HistoryResource, query)
  end

  def list_since(date : Time? = nil, event_type : Radarr::MovieHistoryEventType? = nil, include_movie : Bool? = nil) : Array(Radarr::Model::HistoryResource)
    query = Radarr::Query.new
    query.add("date", date)
    query.add("eventType", event_type)
    query.add("includeMovie", include_movie)
    @client.request_many(:get, "/api/v3/history/since", Radarr::Model::HistoryResource, query)
  end
end
