# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::HostConfig
  def initialize(@client : Radarr::Client)
  end

  def list_host : Radarr::Model::HostConfigResource?
    @client.request_one(:get, "/api/v3/config/host", Radarr::Model::HostConfigResource)
  end

  def get_host(id : Int32) : Radarr::Model::HostConfigResource?
    @client.request_one(:get, "/api/v3/config/host/#{id}", Radarr::Model::HostConfigResource)
  end

  def update_host(id : Int32, body : Radarr::Model::HostConfigResource) : Radarr::Model::HostConfigResource?
    @client.request_one(:put, "/api/v3/config/host/#{id}", Radarr::Model::HostConfigResource, nil, body)
  end
end
