# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::ImportListConfig
  def initialize(@client : Radarr::Client)
  end

  def list_importlist : Radarr::Model::ImportListConfigResource?
    @client.request_one(:get, "/api/v3/config/importlist", Radarr::Model::ImportListConfigResource)
  end

  def get_importlist(id : Int32) : Radarr::Model::ImportListConfigResource?
    @client.request_one(:get, "/api/v3/config/importlist/#{id}", Radarr::Model::ImportListConfigResource)
  end

  def update_importlist(id : Int32, body : Radarr::Model::ImportListConfigResource) : Radarr::Model::ImportListConfigResource?
    @client.request_one(:put, "/api/v3/config/importlist/#{id}", Radarr::Model::ImportListConfigResource, nil, body)
  end
end
