# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::ImportList
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::ImportListResource)
    @client.request_many(:get, "/api/v3/importlist", Radarr::Model::ImportListResource)
  end

  def create(body : Radarr::Model::ImportListResource, force_save : Bool? = nil) : Radarr::Model::ImportListResource?
    query = Radarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:post, "/api/v3/importlist", Radarr::Model::ImportListResource, query, body)
  end

  def create_action(name : String, body : Radarr::Model::ImportListResource) : Nil
    @client.request(:post, "/api/v3/importlist/action/#{name}", nil, body)
  end

  def update_bulk(body : Radarr::Model::ImportListBulkResource) : Radarr::Model::ImportListResource?
    @client.request_one(:put, "/api/v3/importlist/bulk", Radarr::Model::ImportListResource, nil, body)
  end

  def delete_bulk(body : Radarr::Model::ImportListBulkResource) : Nil
    @client.request(:delete, "/api/v3/importlist/bulk", nil, body)
  end

  def list_schema : Array(Radarr::Model::ImportListResource)
    @client.request_many(:get, "/api/v3/importlist/schema", Radarr::Model::ImportListResource)
  end

  def create_test(body : Radarr::Model::ImportListResource, force_test : Bool? = nil) : Nil
    query = Radarr::Query.new
    query.add("forceTest", force_test)
    @client.request(:post, "/api/v3/importlist/test", query, body)
  end

  def create_testall : Nil
    @client.request(:post, "/api/v3/importlist/testall")
  end

  def get(id : Int32) : Radarr::Model::ImportListResource?
    @client.request_one(:get, "/api/v3/importlist/#{id}", Radarr::Model::ImportListResource)
  end

  def update(id : Int32, body : Radarr::Model::ImportListResource, force_save : Bool? = nil) : Radarr::Model::ImportListResource?
    query = Radarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:put, "/api/v3/importlist/#{id}", Radarr::Model::ImportListResource, query, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/importlist/#{id}")
  end
end
