# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::ImportListExclusion
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::ImportListExclusionResource)
    @client.request_many(:get, "/api/v3/exclusions", Radarr::Model::ImportListExclusionResource)
  end

  def create(body : Radarr::Model::ImportListExclusionResource) : Radarr::Model::ImportListExclusionResource?
    @client.request_one(:post, "/api/v3/exclusions", Radarr::Model::ImportListExclusionResource, nil, body)
  end

  def create_bulk(body : Array(Radarr::Model::ImportListExclusionResource)) : Nil
    @client.request(:post, "/api/v3/exclusions/bulk", nil, body)
  end

  def delete_bulk(body : Radarr::Model::ImportListExclusionBulkResource) : Nil
    @client.request(:delete, "/api/v3/exclusions/bulk", nil, body)
  end

  def list_paged(page : Int32? = nil, page_size : Int32? = nil, sort_key : String? = nil, sort_direction : Radarr::SortDirection? = nil) : Radarr::Model::ImportListExclusionResourcePagingResource?
    query = Radarr::Query.new
    query.add("page", page)
    query.add("pageSize", page_size)
    query.add("sortKey", sort_key)
    query.add("sortDirection", sort_direction)
    @client.request_one(:get, "/api/v3/exclusions/paged", Radarr::Model::ImportListExclusionResourcePagingResource, query)
  end

  def get(id : Int32) : Radarr::Model::ImportListExclusionResource?
    @client.request_one(:get, "/api/v3/exclusions/#{id}", Radarr::Model::ImportListExclusionResource)
  end

  def update(id : Int32, body : Radarr::Model::ImportListExclusionResource) : Radarr::Model::ImportListExclusionResource?
    @client.request_one(:put, "/api/v3/exclusions/#{id}", Radarr::Model::ImportListExclusionResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/exclusions/#{id}")
  end
end
