# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::ImportListMovies
  def initialize(@client : Radarr::Client)
  end

  def list_movie(include_recommendations : Bool? = nil, include_trending : Bool? = nil, include_popular : Bool? = nil) : Nil
    query = Radarr::Query.new
    query.add("includeRecommendations", include_recommendations)
    query.add("includeTrending", include_trending)
    query.add("includePopular", include_popular)
    @client.request(:get, "/api/v3/importlist/movie", query)
  end

  def create_movie(body : Array(Radarr::Model::MovieResource)) : Nil
    @client.request(:post, "/api/v3/importlist/movie", nil, body)
  end
end
