# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::IndexerFlag
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::IndexerFlagResource)
    @client.request_many(:get, "/api/v3/indexerflag", Radarr::Model::IndexerFlagResource)
  end
end
