# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::IndexerConfig
  def initialize(@client : Radarr::Client)
  end

  def list_indexer : Radarr::Model::IndexerConfigResource?
    @client.request_one(:get, "/api/v3/config/indexer", Radarr::Model::IndexerConfigResource)
  end

  def get_indexer(id : Int32) : Radarr::Model::IndexerConfigResource?
    @client.request_one(:get, "/api/v3/config/indexer/#{id}", Radarr::Model::IndexerConfigResource)
  end

  def update_indexer(id : Int32, body : Radarr::Model::IndexerConfigResource) : Radarr::Model::IndexerConfigResource?
    @client.request_one(:put, "/api/v3/config/indexer/#{id}", Radarr::Model::IndexerConfigResource, nil, body)
  end
end
