# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Indexer
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::IndexerResource)
    @client.request_many(:get, "/api/v3/indexer", Radarr::Model::IndexerResource)
  end

  def create(body : Radarr::Model::IndexerResource, force_save : Bool? = nil) : Radarr::Model::IndexerResource?
    query = Radarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:post, "/api/v3/indexer", Radarr::Model::IndexerResource, query, body)
  end

  def create_action(name : String, body : Radarr::Model::IndexerResource) : Nil
    @client.request(:post, "/api/v3/indexer/action/#{name}", nil, body)
  end

  def update_bulk(body : Radarr::Model::IndexerBulkResource) : Radarr::Model::IndexerResource?
    @client.request_one(:put, "/api/v3/indexer/bulk", Radarr::Model::IndexerResource, nil, body)
  end

  def delete_bulk(body : Radarr::Model::IndexerBulkResource) : Nil
    @client.request(:delete, "/api/v3/indexer/bulk", nil, body)
  end

  def list_schema : Array(Radarr::Model::IndexerResource)
    @client.request_many(:get, "/api/v3/indexer/schema", Radarr::Model::IndexerResource)
  end

  def create_test(body : Radarr::Model::IndexerResource, force_test : Bool? = nil) : Nil
    query = Radarr::Query.new
    query.add("forceTest", force_test)
    @client.request(:post, "/api/v3/indexer/test", query, body)
  end

  def create_testall : Nil
    @client.request(:post, "/api/v3/indexer/testall")
  end

  def get(id : Int32) : Radarr::Model::IndexerResource?
    @client.request_one(:get, "/api/v3/indexer/#{id}", Radarr::Model::IndexerResource)
  end

  def update(id : Int32, body : Radarr::Model::IndexerResource, force_save : Bool? = nil) : Radarr::Model::IndexerResource?
    query = Radarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:put, "/api/v3/indexer/#{id}", Radarr::Model::IndexerResource, query, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/indexer/#{id}")
  end
end
