# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Language
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::LanguageResource)
    @client.request_many(:get, "/api/v3/language", Radarr::Model::LanguageResource)
  end

  def get(id : Int32) : Radarr::Model::LanguageResource?
    @client.request_one(:get, "/api/v3/language/#{id}", Radarr::Model::LanguageResource)
  end
end
