# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Localization
  def initialize(@client : Radarr::Client)
  end

  def list : String?
    @client.request_one(:get, "/api/v3/localization", String)
  end

  def list_language : Radarr::Model::LocalizationLanguageResource?
    @client.request_one(:get, "/api/v3/localization/language", Radarr::Model::LocalizationLanguageResource)
  end
end
