# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Log
  def initialize(@client : Radarr::Client)
  end

  def list(page : Int32? = nil, page_size : Int32? = nil, sort_key : String? = nil, sort_direction : Radarr::SortDirection? = nil, level : String? = nil) : Radarr::Model::LogResourcePagingResource?
    query = Radarr::Query.new
    query.add("page", page)
    query.add("pageSize", page_size)
    query.add("sortKey", sort_key)
    query.add("sortDirection", sort_direction)
    query.add("level", level)
    @client.request_one(:get, "/api/v3/log", Radarr::Model::LogResourcePagingResource, query)
  end
end
