# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::LogFile
  def initialize(@client : Radarr::Client)
  end

  def list_file : Array(Radarr::Model::LogFileResource)
    @client.request_many(:get, "/api/v3/log/file", Radarr::Model::LogFileResource)
  end

  def get_file(filename : String) : Nil
    @client.request(:get, "/api/v3/log/file/#{filename}")
  end
end
