# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::ManualImport
  def initialize(@client : Radarr::Client)
  end

  def list(folder : String? = nil, download_id : String? = nil, movie_id : Int32? = nil, filter_existing_files : Bool? = nil) : Array(Radarr::Model::ManualImportResource)
    query = Radarr::Query.new
    query.add("folder", folder)
    query.add("downloadId", download_id)
    query.add("movieId", movie_id)
    query.add("filterExistingFiles", filter_existing_files)
    @client.request_many(:get, "/api/v3/manualimport", Radarr::Model::ManualImportResource, query)
  end

  def create(body : Array(Radarr::Model::ManualImportReprocessResource)) : Nil
    @client.request(:post, "/api/v3/manualimport", nil, body)
  end
end
