# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::MediaManagementConfig
  def initialize(@client : Radarr::Client)
  end

  def list_mediamanagement : Radarr::Model::MediaManagementConfigResource?
    @client.request_one(:get, "/api/v3/config/mediamanagement", Radarr::Model::MediaManagementConfigResource)
  end

  def get_mediamanagement(id : Int32) : Radarr::Model::MediaManagementConfigResource?
    @client.request_one(:get, "/api/v3/config/mediamanagement/#{id}", Radarr::Model::MediaManagementConfigResource)
  end

  def update_mediamanagement(id : Int32, body : Radarr::Model::MediaManagementConfigResource) : Radarr::Model::MediaManagementConfigResource?
    @client.request_one(:put, "/api/v3/config/mediamanagement/#{id}", Radarr::Model::MediaManagementConfigResource, nil, body)
  end
end
