# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Metadata
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::MetadataResource)
    @client.request_many(:get, "/api/v3/metadata", Radarr::Model::MetadataResource)
  end

  def create(body : Radarr::Model::MetadataResource, force_save : Bool? = nil) : Radarr::Model::MetadataResource?
    query = Radarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:post, "/api/v3/metadata", Radarr::Model::MetadataResource, query, body)
  end

  def create_action(name : String, body : Radarr::Model::MetadataResource) : Nil
    @client.request(:post, "/api/v3/metadata/action/#{name}", nil, body)
  end

  def list_schema : Array(Radarr::Model::MetadataResource)
    @client.request_many(:get, "/api/v3/metadata/schema", Radarr::Model::MetadataResource)
  end

  def create_test(body : Radarr::Model::MetadataResource, force_test : Bool? = nil) : Nil
    query = Radarr::Query.new
    query.add("forceTest", force_test)
    @client.request(:post, "/api/v3/metadata/test", query, body)
  end

  def create_testall : Nil
    @client.request(:post, "/api/v3/metadata/testall")
  end

  def get(id : Int32) : Radarr::Model::MetadataResource?
    @client.request_one(:get, "/api/v3/metadata/#{id}", Radarr::Model::MetadataResource)
  end

  def update(id : Int32, body : Radarr::Model::MetadataResource, force_save : Bool? = nil) : Radarr::Model::MetadataResource?
    query = Radarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:put, "/api/v3/metadata/#{id}", Radarr::Model::MetadataResource, query, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/metadata/#{id}")
  end
end
