# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::MetadataConfig
  def initialize(@client : Radarr::Client)
  end

  def list_metadata : Radarr::Model::MetadataConfigResource?
    @client.request_one(:get, "/api/v3/config/metadata", Radarr::Model::MetadataConfigResource)
  end

  def get_metadata(id : Int32) : Radarr::Model::MetadataConfigResource?
    @client.request_one(:get, "/api/v3/config/metadata/#{id}", Radarr::Model::MetadataConfigResource)
  end

  def update_metadata(id : Int32, body : Radarr::Model::MetadataConfigResource) : Radarr::Model::MetadataConfigResource?
    @client.request_one(:put, "/api/v3/config/metadata/#{id}", Radarr::Model::MetadataConfigResource, nil, body)
  end
end
