# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Missing
  def initialize(@client : Radarr::Client)
  end

  def list_missing(page : Int32? = nil, page_size : Int32? = nil, sort_key : String? = nil, sort_direction : Radarr::SortDirection? = nil, monitored : Bool? = nil) : Radarr::Model::MovieResourcePagingResource?
    query = Radarr::Query.new
    query.add("page", page)
    query.add("pageSize", page_size)
    query.add("sortKey", sort_key)
    query.add("sortDirection", sort_direction)
    query.add("monitored", monitored)
    @client.request_one(:get, "/api/v3/wanted/missing", Radarr::Model::MovieResourcePagingResource, query)
  end
end
