# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::MovieEditor
  def initialize(@client : Radarr::Client)
  end

  def update_editor(body : Radarr::Model::MovieEditorResource) : Nil
    @client.request(:put, "/api/v3/movie/editor", nil, body)
  end

  def delete_editor(body : Radarr::Model::MovieEditorResource) : Nil
    @client.request(:delete, "/api/v3/movie/editor", nil, body)
  end
end
