# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::MovieFile
  def initialize(@client : Radarr::Client)
  end

  def list(movie_id : Array(Int32)? = nil, movie_file_ids : Array(Int32)? = nil) : Array(Radarr::Model::MovieFileResource)
    query = Radarr::Query.new
    query.add("movieId", movie_id)
    query.add("movieFileIds", movie_file_ids)
    @client.request_many(:get, "/api/v3/moviefile", Radarr::Model::MovieFileResource, query)
  end

  def update_bulk(body : Array(Radarr::Model::MovieFileResource)) : Nil
    @client.request(:put, "/api/v3/moviefile/bulk", nil, body)
  end

  def delete_bulk(body : Radarr::Model::MovieFileListResource) : Nil
    @client.request(:delete, "/api/v3/moviefile/bulk", nil, body)
  end

  def update_editor(body : Radarr::Model::MovieFileListResource) : Nil
    @client.request(:put, "/api/v3/moviefile/editor", nil, body)
  end

  def get(id : Int32) : Radarr::Model::MovieFileResource?
    @client.request_one(:get, "/api/v3/moviefile/#{id}", Radarr::Model::MovieFileResource)
  end

  def update(id : Int32, body : Radarr::Model::MovieFileResource) : Radarr::Model::MovieFileResource?
    @client.request_one(:put, "/api/v3/moviefile/#{id}", Radarr::Model::MovieFileResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/moviefile/#{id}")
  end
end
