# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::MovieLookup
  def initialize(@client : Radarr::Client)
  end

  def list_lookup(term : String? = nil) : Array(Radarr::Model::MovieResource)
    query = Radarr::Query.new
    query.add("term", term)
    @client.request_many(:get, "/api/v3/movie/lookup", Radarr::Model::MovieResource, query)
  end

  def list_lookup_imdb(imdb_id : String? = nil) : Radarr::Model::MovieResource?
    query = Radarr::Query.new
    query.add("imdbId", imdb_id)
    @client.request_one(:get, "/api/v3/movie/lookup/imdb", Radarr::Model::MovieResource, query)
  end

  def list_lookup_tmdb(tmdb_id : Int32? = nil) : Radarr::Model::MovieResource?
    query = Radarr::Query.new
    query.add("tmdbId", tmdb_id)
    @client.request_one(:get, "/api/v3/movie/lookup/tmdb", Radarr::Model::MovieResource, query)
  end
end
