# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::MovieImport
  def initialize(@client : Radarr::Client)
  end

  def create_import(body : Array(Radarr::Model::MovieResource)) : Array(Radarr::Model::MovieResource)
    @client.request_many(:post, "/api/v3/movie/import", Radarr::Model::MovieResource, nil, body)
  end
end
