# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Movie
  def initialize(@client : Radarr::Client)
  end

  def list(tmdb_id : Int32? = nil, exclude_local_covers : Bool? = nil, language_id : Int32? = nil) : Array(Radarr::Model::MovieResource)
    query = Radarr::Query.new
    query.add("tmdbId", tmdb_id)
    query.add("excludeLocalCovers", exclude_local_covers)
    query.add("languageId", language_id)
    @client.request_many(:get, "/api/v3/movie", Radarr::Model::MovieResource, query)
  end

  def create(body : Radarr::Model::MovieResource) : Radarr::Model::MovieResource?
    @client.request_one(:post, "/api/v3/movie", Radarr::Model::MovieResource, nil, body)
  end

  def get(id : Int32) : Radarr::Model::MovieResource?
    @client.request_one(:get, "/api/v3/movie/#{id}", Radarr::Model::MovieResource)
  end

  def update(id : Int32, body : Radarr::Model::MovieResource, move_files : Bool? = nil) : Radarr::Model::MovieResource?
    query = Radarr::Query.new
    query.add("moveFiles", move_files)
    @client.request_one(:put, "/api/v3/movie/#{id}", Radarr::Model::MovieResource, query, body)
  end

  def delete(id : Int32, delete_files : Bool? = nil, add_import_exclusion : Bool? = nil) : Nil
    query = Radarr::Query.new
    query.add("deleteFiles", delete_files)
    query.add("addImportExclusion", add_import_exclusion)
    @client.request(:delete, "/api/v3/movie/#{id}", query)
  end
end
