# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::MovieFolder
  def initialize(@client : Radarr::Client)
  end

  def list_folder(id : Int32) : Nil
    @client.request(:get, "/api/v3/movie/#{id}/folder")
  end
end
