# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::NamingConfig
  def initialize(@client : Radarr::Client)
  end

  def list_naming : Radarr::Model::NamingConfigResource?
    @client.request_one(:get, "/api/v3/config/naming", Radarr::Model::NamingConfigResource)
  end

  def list_naming_examples(rename_movies : Bool? = nil, replace_illegal_characters : Bool? = nil, colon_replacement_format : Radarr::ColonReplacementFormat? = nil, standard_movie_format : String? = nil, movie_folder_format : String? = nil, id : Int32? = nil, resource_name : String? = nil) : Nil
    query = Radarr::Query.new
    query.add("renameMovies", rename_movies)
    query.add("replaceIllegalCharacters", replace_illegal_characters)
    query.add("colonReplacementFormat", colon_replacement_format)
    query.add("standardMovieFormat", standard_movie_format)
    query.add("movieFolderFormat", movie_folder_format)
    query.add("id", id)
    query.add("resourceName", resource_name)
    @client.request(:get, "/api/v3/config/naming/examples", query)
  end

  def get_naming(id : Int32) : Radarr::Model::NamingConfigResource?
    @client.request_one(:get, "/api/v3/config/naming/#{id}", Radarr::Model::NamingConfigResource)
  end

  def update_naming(id : Int32, body : Radarr::Model::NamingConfigResource) : Radarr::Model::NamingConfigResource?
    @client.request_one(:put, "/api/v3/config/naming/#{id}", Radarr::Model::NamingConfigResource, nil, body)
  end
end
