# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Notification
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::NotificationResource)
    @client.request_many(:get, "/api/v3/notification", Radarr::Model::NotificationResource)
  end

  def create(body : Radarr::Model::NotificationResource, force_save : Bool? = nil) : Radarr::Model::NotificationResource?
    query = Radarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:post, "/api/v3/notification", Radarr::Model::NotificationResource, query, body)
  end

  def create_action(name : String, body : Radarr::Model::NotificationResource) : Nil
    @client.request(:post, "/api/v3/notification/action/#{name}", nil, body)
  end

  def list_schema : Array(Radarr::Model::NotificationResource)
    @client.request_many(:get, "/api/v3/notification/schema", Radarr::Model::NotificationResource)
  end

  def create_test(body : Radarr::Model::NotificationResource, force_test : Bool? = nil) : Nil
    query = Radarr::Query.new
    query.add("forceTest", force_test)
    @client.request(:post, "/api/v3/notification/test", query, body)
  end

  def create_testall : Nil
    @client.request(:post, "/api/v3/notification/testall")
  end

  def get(id : Int32) : Radarr::Model::NotificationResource?
    @client.request_one(:get, "/api/v3/notification/#{id}", Radarr::Model::NotificationResource)
  end

  def update(id : Int32, body : Radarr::Model::NotificationResource, force_save : Bool? = nil) : Radarr::Model::NotificationResource?
    query = Radarr::Query.new
    query.add("forceSave", force_save)
    @client.request_one(:put, "/api/v3/notification/#{id}", Radarr::Model::NotificationResource, query, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/notification/#{id}")
  end
end
