# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Parse
  def initialize(@client : Radarr::Client)
  end

  def list(title : String? = nil) : Radarr::Model::ParseResource?
    query = Radarr::Query.new
    query.add("title", title)
    @client.request_one(:get, "/api/v3/parse", Radarr::Model::ParseResource, query)
  end
end
