# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Ping
  def initialize(@client : Radarr::Client)
  end

  def list : Radarr::Model::PingResource?
    @client.request_one(:get, "/ping", Radarr::Model::PingResource)
  end
end
