# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::QualityProfile
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::QualityProfileResource)
    @client.request_many(:get, "/api/v3/qualityprofile", Radarr::Model::QualityProfileResource)
  end

  def create(body : Radarr::Model::QualityProfileResource) : Radarr::Model::QualityProfileResource?
    @client.request_one(:post, "/api/v3/qualityprofile", Radarr::Model::QualityProfileResource, nil, body)
  end

  def get(id : Int32) : Radarr::Model::QualityProfileResource?
    @client.request_one(:get, "/api/v3/qualityprofile/#{id}", Radarr::Model::QualityProfileResource)
  end

  def update(id : Int32, body : Radarr::Model::QualityProfileResource) : Radarr::Model::QualityProfileResource?
    @client.request_one(:put, "/api/v3/qualityprofile/#{id}", Radarr::Model::QualityProfileResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/qualityprofile/#{id}")
  end
end
