# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::QualityDefinition
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::QualityDefinitionResource)
    @client.request_many(:get, "/api/v3/qualitydefinition", Radarr::Model::QualityDefinitionResource)
  end

  def list_limits : Radarr::Model::QualityDefinitionLimitsResource?
    @client.request_one(:get, "/api/v3/qualitydefinition/limits", Radarr::Model::QualityDefinitionLimitsResource)
  end

  def update_update(body : Array(Radarr::Model::QualityDefinitionResource)) : Nil
    @client.request(:put, "/api/v3/qualitydefinition/update", nil, body)
  end

  def get(id : Int32) : Radarr::Model::QualityDefinitionResource?
    @client.request_one(:get, "/api/v3/qualitydefinition/#{id}", Radarr::Model::QualityDefinitionResource)
  end

  def update(id : Int32, body : Radarr::Model::QualityDefinitionResource) : Radarr::Model::QualityDefinitionResource?
    @client.request_one(:put, "/api/v3/qualitydefinition/#{id}", Radarr::Model::QualityDefinitionResource, nil, body)
  end
end
