# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::QualityProfileSchema
  def initialize(@client : Radarr::Client)
  end

  def list_schema : Radarr::Model::QualityProfileResource?
    @client.request_one(:get, "/api/v3/qualityprofile/schema", Radarr::Model::QualityProfileResource)
  end
end
