# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::QueueStatus
  def initialize(@client : Radarr::Client)
  end

  def list_status : Radarr::Model::QueueStatusResource?
    @client.request_one(:get, "/api/v3/queue/status", Radarr::Model::QueueStatusResource)
  end
end
