# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Queue
  def initialize(@client : Radarr::Client)
  end

  def list(page : Int32? = nil, page_size : Int32? = nil, sort_key : String? = nil, sort_direction : Radarr::SortDirection? = nil, include_unknown_movie_items : Bool? = nil, include_movie : Bool? = nil, movie_ids : Array(Int32)? = nil, protocol : Radarr::DownloadProtocol? = nil, languages : Array(Int32)? = nil, quality : Array(Int32)? = nil, status : Array(Radarr::QueueStatus)? = nil) : Radarr::Model::QueueResourcePagingResource?
    query = Radarr::Query.new
    query.add("page", page)
    query.add("pageSize", page_size)
    query.add("sortKey", sort_key)
    query.add("sortDirection", sort_direction)
    query.add("includeUnknownMovieItems", include_unknown_movie_items)
    query.add("includeMovie", include_movie)
    query.add("movieIds", movie_ids)
    query.add("protocol", protocol)
    query.add("languages", languages)
    query.add("quality", quality)
    query.add("status", status)
    @client.request_one(:get, "/api/v3/queue", Radarr::Model::QueueResourcePagingResource, query)
  end

  def delete_bulk(body : Radarr::Model::QueueBulkResource, remove_from_client : Bool? = nil, blocklist : Bool? = nil, skip_redownload : Bool? = nil, change_category : Bool? = nil) : Nil
    query = Radarr::Query.new
    query.add("removeFromClient", remove_from_client)
    query.add("blocklist", blocklist)
    query.add("skipRedownload", skip_redownload)
    query.add("changeCategory", change_category)
    @client.request(:delete, "/api/v3/queue/bulk", query, body)
  end

  def delete(id : Int32, remove_from_client : Bool? = nil, blocklist : Bool? = nil, skip_redownload : Bool? = nil, change_category : Bool? = nil) : Nil
    query = Radarr::Query.new
    query.add("removeFromClient", remove_from_client)
    query.add("blocklist", blocklist)
    query.add("skipRedownload", skip_redownload)
    query.add("changeCategory", change_category)
    @client.request(:delete, "/api/v3/queue/#{id}", query)
  end
end
