# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::QueueAction
  def initialize(@client : Radarr::Client)
  end

  def create_grab_bulk(body : Radarr::Model::QueueBulkResource) : Nil
    @client.request(:post, "/api/v3/queue/grab/bulk", nil, body)
  end

  def create_grab(id : Int32) : Nil
    @client.request(:post, "/api/v3/queue/grab/#{id}")
  end
end
