# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::QueueDetails
  def initialize(@client : Radarr::Client)
  end

  def list_details(movie_id : Int32? = nil, include_movie : Bool? = nil) : Array(Radarr::Model::QueueResource)
    query = Radarr::Query.new
    query.add("movieId", movie_id)
    query.add("includeMovie", include_movie)
    @client.request_many(:get, "/api/v3/queue/details", Radarr::Model::QueueResource, query)
  end
end
