# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::ReleaseProfile
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::ReleaseProfileResource)
    @client.request_many(:get, "/api/v3/releaseprofile", Radarr::Model::ReleaseProfileResource)
  end

  def create(body : Radarr::Model::ReleaseProfileResource) : Radarr::Model::ReleaseProfileResource?
    @client.request_one(:post, "/api/v3/releaseprofile", Radarr::Model::ReleaseProfileResource, nil, body)
  end

  def get(id : Int32) : Radarr::Model::ReleaseProfileResource?
    @client.request_one(:get, "/api/v3/releaseprofile/#{id}", Radarr::Model::ReleaseProfileResource)
  end

  def update(id : Int32, body : Radarr::Model::ReleaseProfileResource) : Radarr::Model::ReleaseProfileResource?
    @client.request_one(:put, "/api/v3/releaseprofile/#{id}", Radarr::Model::ReleaseProfileResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/releaseprofile/#{id}")
  end
end
