# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::ReleasePush
  def initialize(@client : Radarr::Client)
  end

  def create_push(body : Radarr::Model::ReleaseResource) : Array(Radarr::Model::ReleaseResource)
    @client.request_many(:post, "/api/v3/release/push", Radarr::Model::ReleaseResource, nil, body)
  end
end
