# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Release
  def initialize(@client : Radarr::Client)
  end

  def list(movie_id : Int32? = nil) : Array(Radarr::Model::ReleaseResource)
    query = Radarr::Query.new
    query.add("movieId", movie_id)
    @client.request_many(:get, "/api/v3/release", Radarr::Model::ReleaseResource, query)
  end

  def create(body : Radarr::Model::ReleaseResource) : Nil
    @client.request(:post, "/api/v3/release", nil, body)
  end
end
