# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::RemotePathMapping
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::RemotePathMappingResource)
    @client.request_many(:get, "/api/v3/remotepathmapping", Radarr::Model::RemotePathMappingResource)
  end

  def create(body : Radarr::Model::RemotePathMappingResource) : Radarr::Model::RemotePathMappingResource?
    @client.request_one(:post, "/api/v3/remotepathmapping", Radarr::Model::RemotePathMappingResource, nil, body)
  end

  def get(id : Int32) : Radarr::Model::RemotePathMappingResource?
    @client.request_one(:get, "/api/v3/remotepathmapping/#{id}", Radarr::Model::RemotePathMappingResource)
  end

  def update(id : Int32, body : Radarr::Model::RemotePathMappingResource) : Radarr::Model::RemotePathMappingResource?
    @client.request_one(:put, "/api/v3/remotepathmapping/#{id}", Radarr::Model::RemotePathMappingResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/remotepathmapping/#{id}")
  end
end
