# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::RenameMovie
  def initialize(@client : Radarr::Client)
  end

  def list(movie_id : Array(Int32)? = nil) : Array(Radarr::Model::RenameMovieResource)
    query = Radarr::Query.new
    query.add("movieId", movie_id)
    @client.request_many(:get, "/api/v3/rename", Radarr::Model::RenameMovieResource, query)
  end
end
