# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::RootFolder
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::RootFolderResource)
    @client.request_many(:get, "/api/v3/rootfolder", Radarr::Model::RootFolderResource)
  end

  def create(body : Radarr::Model::RootFolderResource) : Radarr::Model::RootFolderResource?
    @client.request_one(:post, "/api/v3/rootfolder", Radarr::Model::RootFolderResource, nil, body)
  end

  def get(id : Int32) : Radarr::Model::RootFolderResource?
    @client.request_one(:get, "/api/v3/rootfolder/#{id}", Radarr::Model::RootFolderResource)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/rootfolder/#{id}")
  end
end
