# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Tag
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::TagResource)
    @client.request_many(:get, "/api/v3/tag", Radarr::Model::TagResource)
  end

  def create(body : Radarr::Model::TagResource) : Radarr::Model::TagResource?
    @client.request_one(:post, "/api/v3/tag", Radarr::Model::TagResource, nil, body)
  end

  def get(id : Int32) : Radarr::Model::TagResource?
    @client.request_one(:get, "/api/v3/tag/#{id}", Radarr::Model::TagResource)
  end

  def update(id : Int32, body : Radarr::Model::TagResource) : Radarr::Model::TagResource?
    @client.request_one(:put, "/api/v3/tag/#{id}", Radarr::Model::TagResource, nil, body)
  end

  def delete(id : Int32) : Nil
    @client.request(:delete, "/api/v3/tag/#{id}")
  end
end
