# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::TagDetails
  def initialize(@client : Radarr::Client)
  end

  def list_detail : Array(Radarr::Model::TagDetailsResource)
    @client.request_many(:get, "/api/v3/tag/detail", Radarr::Model::TagDetailsResource)
  end

  def get_detail(id : Int32) : Radarr::Model::TagDetailsResource?
    @client.request_one(:get, "/api/v3/tag/detail/#{id}", Radarr::Model::TagDetailsResource)
  end
end
