# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Task
  def initialize(@client : Radarr::Client)
  end

  def list_task : Array(Radarr::Model::TaskResource)
    @client.request_many(:get, "/api/v3/system/task", Radarr::Model::TaskResource)
  end

  def get_task(id : Int32) : Radarr::Model::TaskResource?
    @client.request_one(:get, "/api/v3/system/task/#{id}", Radarr::Model::TaskResource)
  end
end
