# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::UiConfig
  def initialize(@client : Radarr::Client)
  end

  def list_ui : Radarr::Model::UiConfigResource?
    @client.request_one(:get, "/api/v3/config/ui", Radarr::Model::UiConfigResource)
  end

  def get_ui(id : Int32) : Radarr::Model::UiConfigResource?
    @client.request_one(:get, "/api/v3/config/ui/#{id}", Radarr::Model::UiConfigResource)
  end

  def update_ui(id : Int32, body : Radarr::Model::UiConfigResource) : Radarr::Model::UiConfigResource?
    @client.request_one(:put, "/api/v3/config/ui/#{id}", Radarr::Model::UiConfigResource, nil, body)
  end
end
