# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::UpdateLogFile
  def initialize(@client : Radarr::Client)
  end

  def list_file_update : Array(Radarr::Model::LogFileResource)
    @client.request_many(:get, "/api/v3/log/file/update", Radarr::Model::LogFileResource)
  end

  def get_file_update(filename : String) : Nil
    @client.request(:get, "/api/v3/log/file/update/#{filename}")
  end
end
