# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Api::Update
  def initialize(@client : Radarr::Client)
  end

  def list : Array(Radarr::Model::UpdateResource)
    @client.request_many(:get, "/api/v3/update", Radarr::Model::UpdateResource)
  end
end
