# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::AddMovieOptions < Radarr::Model
  @[JSON::Field(key: "ignoreEpisodesWithFiles")]
  property ignore_episodes_with_files : Bool?

  @[JSON::Field(key: "ignoreEpisodesWithoutFiles")]
  property ignore_episodes_without_files : Bool?

  @[JSON::Field(key: "monitor")]
  property monitor : Radarr::MonitorTypes?

  @[JSON::Field(key: "searchForMovie")]
  property search_for_movie : Bool?

  @[JSON::Field(key: "addMethod")]
  property add_method : Radarr::AddMovieMethod?
end
