# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::AlternativeTitleResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "sourceType")]
  property source_type : Radarr::SourceType?

  @[JSON::Field(key: "movieMetadataId")]
  property movie_metadata_id : Int32?

  @[JSON::Field(key: "title")]
  property title : String?

  @[JSON::Field(key: "cleanTitle")]
  property clean_title : String?
end
