# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::ApiInfoResource < Radarr::Model
  @[JSON::Field(key: "current")]
  property current : String?

  @[JSON::Field(key: "deprecated")]
  property deprecated = [] of String
end
