# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::BackupResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "path")]
  property path : String?

  @[JSON::Field(key: "type")]
  property type_field : Radarr::BackupType?

  @[JSON::Field(key: "size")]
  property size : Int64?

  @[JSON::Field(key: "time", converter: Radarr::TimeConverter)]
  property time : Time?
end
