# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::BlocklistBulkResource < Radarr::Model
  @[JSON::Field(key: "ids")]
  property ids = [] of Int32
end
