# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::BlocklistResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "movieId")]
  property movie_id : Int32?

  @[JSON::Field(key: "sourceTitle")]
  property source_title : String?

  @[JSON::Field(key: "languages")]
  property languages = [] of Radarr::Model::Language

  @[JSON::Field(key: "quality")]
  property quality : Radarr::Model::QualityModel?

  @[JSON::Field(key: "customFormats")]
  property custom_formats = [] of Radarr::Model::CustomFormatResource

  @[JSON::Field(key: "date", converter: Radarr::TimeConverter)]
  property date : Time?

  @[JSON::Field(key: "protocol")]
  property protocol : Radarr::DownloadProtocol?

  @[JSON::Field(key: "indexer")]
  property indexer : String?

  @[JSON::Field(key: "message")]
  property message : String?

  @[JSON::Field(key: "movie")]
  property movie : Radarr::Model::MovieResource?
end
