# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::CollectionResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "title")]
  property title : String?

  @[JSON::Field(key: "sortTitle")]
  property sort_title : String?

  @[JSON::Field(key: "tmdbId")]
  property tmdb_id : Int32?

  @[JSON::Field(key: "images")]
  property images = [] of Radarr::Model::MediaCover

  @[JSON::Field(key: "overview")]
  property overview : String?

  @[JSON::Field(key: "monitored")]
  property monitored : Bool?

  @[JSON::Field(key: "rootFolderPath")]
  property root_folder_path : String?

  @[JSON::Field(key: "qualityProfileId")]
  property quality_profile_id : Int32?

  @[JSON::Field(key: "searchOnAdd")]
  property search_on_add : Bool?

  @[JSON::Field(key: "minimumAvailability")]
  property minimum_availability : Radarr::MovieStatusType?

  @[JSON::Field(key: "movies")]
  property movies = [] of Radarr::Model::CollectionMovieResource

  @[JSON::Field(key: "missingMovies")]
  property missing_movies : Int32?

  @[JSON::Field(key: "tags")]
  property tags = [] of Int32
end
