# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::CollectionUpdateResource < Radarr::Model
  @[JSON::Field(key: "collectionIds")]
  property collection_ids = [] of Int32

  @[JSON::Field(key: "monitored")]
  property monitored : Bool?

  @[JSON::Field(key: "monitorMovies")]
  property monitor_movies : Bool?

  @[JSON::Field(key: "searchOnAdd")]
  property search_on_add : Bool?

  @[JSON::Field(key: "qualityProfileId")]
  property quality_profile_id : Int32?

  @[JSON::Field(key: "rootFolderPath")]
  property root_folder_path : String?

  @[JSON::Field(key: "minimumAvailability")]
  property minimum_availability : Radarr::MovieStatusType?
end
