# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::CollectionMovieResource < Radarr::Model
  @[JSON::Field(key: "tmdbId")]
  property tmdb_id : Int32?

  @[JSON::Field(key: "imdbId")]
  property imdb_id : String?

  @[JSON::Field(key: "title")]
  property title : String?

  @[JSON::Field(key: "cleanTitle")]
  property clean_title : String?

  @[JSON::Field(key: "sortTitle")]
  property sort_title : String?

  @[JSON::Field(key: "status")]
  property status : Radarr::MovieStatusType?

  @[JSON::Field(key: "overview")]
  property overview : String?

  @[JSON::Field(key: "runtime")]
  property runtime : Int32?

  @[JSON::Field(key: "images")]
  property images = [] of Radarr::Model::MediaCover

  @[JSON::Field(key: "year")]
  property year : Int32?

  @[JSON::Field(key: "ratings")]
  property ratings : Radarr::Model::Ratings?

  @[JSON::Field(key: "genres")]
  property genres = [] of String

  @[JSON::Field(key: "folder")]
  property folder : String?

  @[JSON::Field(key: "isExisting")]
  property is_existing : Bool?

  @[JSON::Field(key: "isExcluded")]
  property is_excluded : Bool?
end
