# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::CommandResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "commandName")]
  property command_name : String?

  @[JSON::Field(key: "message")]
  property message : String?

  @[JSON::Field(key: "body")]
  property body : Radarr::Model::Command?

  @[JSON::Field(key: "priority")]
  property priority : Radarr::CommandPriority?

  @[JSON::Field(key: "status")]
  property status : Radarr::CommandStatus?

  @[JSON::Field(key: "result")]
  property result : Radarr::CommandResult?

  @[JSON::Field(key: "queued", converter: Radarr::TimeConverter)]
  property queued : Time?

  @[JSON::Field(key: "started", converter: Radarr::TimeConverter)]
  property started : Time?

  @[JSON::Field(key: "ended", converter: Radarr::TimeConverter)]
  property ended : Time?

  @[JSON::Field(key: "duration")]
  property duration : String?

  @[JSON::Field(key: "exception")]
  property exception : String?

  @[JSON::Field(key: "trigger")]
  property trigger : Radarr::CommandTrigger?

  @[JSON::Field(key: "clientUserAgent")]
  property client_user_agent : String?

  @[JSON::Field(key: "stateChangeTime", converter: Radarr::TimeConverter)]
  property state_change_time : Time?

  @[JSON::Field(key: "sendUpdatesToClient")]
  property send_updates_to_client : Bool?

  @[JSON::Field(key: "updateScheduledTask")]
  property update_scheduled_task : Bool?

  @[JSON::Field(key: "lastExecutionTime", converter: Radarr::TimeConverter)]
  property last_execution_time : Time?
end
