# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::CreditResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "personName")]
  property person_name : String?

  @[JSON::Field(key: "creditTmdbId")]
  property credit_tmdb_id : String?

  @[JSON::Field(key: "personTmdbId")]
  property person_tmdb_id : Int32?

  @[JSON::Field(key: "movieMetadataId")]
  property movie_metadata_id : Int32?

  @[JSON::Field(key: "images")]
  property images = [] of Radarr::Model::MediaCover

  @[JSON::Field(key: "department")]
  property department : String?

  @[JSON::Field(key: "job")]
  property job : String?

  @[JSON::Field(key: "character")]
  property character : String?

  @[JSON::Field(key: "order")]
  property order : Int32?

  @[JSON::Field(key: "type")]
  property type_field : Radarr::CreditType?
end
