# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::DiskSpaceResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "path")]
  property path : String?

  @[JSON::Field(key: "label")]
  property label : String?

  @[JSON::Field(key: "freeSpace")]
  property free_space : Int64?

  @[JSON::Field(key: "totalSpace")]
  property total_space : Int64?
end
