# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::DownloadClientConfigResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "downloadClientWorkingFolders")]
  property download_client_working_folders : String?

  @[JSON::Field(key: "enableCompletedDownloadHandling")]
  property enable_completed_download_handling : Bool?

  @[JSON::Field(key: "checkForFinishedDownloadInterval")]
  property check_for_finished_download_interval : Int32?

  @[JSON::Field(key: "autoRedownloadFailed")]
  property auto_redownload_failed : Bool?

  @[JSON::Field(key: "autoRedownloadFailedFromInteractiveSearch")]
  property auto_redownload_failed_from_interactive_search : Bool?
end
