# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::ExtraFileResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "movieId")]
  property movie_id : Int32?

  @[JSON::Field(key: "movieFileId")]
  property movie_file_id : Int32?

  @[JSON::Field(key: "relativePath")]
  property relative_path : String?

  @[JSON::Field(key: "extension")]
  property extension : String?

  @[JSON::Field(key: "languageTags")]
  property language_tags = [] of String

  @[JSON::Field(key: "title")]
  property title : String?

  @[JSON::Field(key: "type")]
  property type_field : Radarr::ExtraFileType?
end
