# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::HealthResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "source")]
  property source : String?

  @[JSON::Field(key: "type")]
  property type_field : Radarr::HealthCheckResult?

  @[JSON::Field(key: "message")]
  property message : String?

  @[JSON::Field(key: "wikiUrl")]
  property wiki_url : String?
end
