# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::HistoryResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "movieId")]
  property movie_id : Int32?

  @[JSON::Field(key: "sourceTitle")]
  property source_title : String?

  @[JSON::Field(key: "languages")]
  property languages = [] of Radarr::Model::Language

  @[JSON::Field(key: "quality")]
  property quality : Radarr::Model::QualityModel?

  @[JSON::Field(key: "customFormats")]
  property custom_formats = [] of Radarr::Model::CustomFormatResource

  @[JSON::Field(key: "customFormatScore")]
  property custom_format_score : Int32?

  @[JSON::Field(key: "qualityCutoffNotMet")]
  property quality_cutoff_not_met : Bool?

  @[JSON::Field(key: "date", converter: Radarr::TimeConverter)]
  property date : Time?

  @[JSON::Field(key: "downloadId")]
  property download_id : String?

  @[JSON::Field(key: "eventType")]
  property event_type : Radarr::MovieHistoryEventType?

  @[JSON::Field(key: "data")]
  property data : Hash(String, String?)?

  @[JSON::Field(key: "movie")]
  property movie : Radarr::Model::MovieResource?
end
