# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::ImportListExclusionResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "fields")]
  property fields = [] of Radarr::Model::Field

  @[JSON::Field(key: "implementationName")]
  property implementation_name : String?

  @[JSON::Field(key: "implementation")]
  property implementation : String?

  @[JSON::Field(key: "configContract")]
  property config_contract : String?

  @[JSON::Field(key: "infoLink")]
  property info_link : String?

  @[JSON::Field(key: "message")]
  property message : Radarr::Model::ProviderMessage?

  @[JSON::Field(key: "tags")]
  property tags = [] of Int32

  @[JSON::Field(key: "presets")]
  property presets = [] of Radarr::Model::ImportListExclusionResource

  @[JSON::Field(key: "tmdbId")]
  property tmdb_id : Int32?

  @[JSON::Field(key: "movieTitle")]
  property movie_title : String?

  @[JSON::Field(key: "movieYear")]
  property movie_year : Int32?
end
