# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::ImportRejectionResource < Radarr::Model
  @[JSON::Field(key: "reason")]
  property reason : String?

  @[JSON::Field(key: "type")]
  property type_field : Radarr::RejectionType?
end
