# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::ImportListResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "fields")]
  property fields = [] of Radarr::Model::Field

  @[JSON::Field(key: "implementationName")]
  property implementation_name : String?

  @[JSON::Field(key: "implementation")]
  property implementation : String?

  @[JSON::Field(key: "configContract")]
  property config_contract : String?

  @[JSON::Field(key: "infoLink")]
  property info_link : String?

  @[JSON::Field(key: "message")]
  property message : Radarr::Model::ProviderMessage?

  @[JSON::Field(key: "tags")]
  property tags = [] of Int32

  @[JSON::Field(key: "presets")]
  property presets = [] of Radarr::Model::ImportListResource

  @[JSON::Field(key: "enabled")]
  property enabled : Bool?

  @[JSON::Field(key: "enableAuto")]
  property enable_auto : Bool?

  @[JSON::Field(key: "monitor")]
  property monitor : Radarr::MonitorTypes?

  @[JSON::Field(key: "rootFolderPath")]
  property root_folder_path : String?

  @[JSON::Field(key: "qualityProfileId")]
  property quality_profile_id : Int32?

  @[JSON::Field(key: "searchOnAdd")]
  property search_on_add : Bool?

  @[JSON::Field(key: "minimumAvailability")]
  property minimum_availability : Radarr::MovieStatusType?

  @[JSON::Field(key: "listType")]
  property list_type : Radarr::ImportListType?

  @[JSON::Field(key: "listOrder")]
  property list_order : Int32?

  @[JSON::Field(key: "minRefreshInterval")]
  property min_refresh_interval : String?
end
