# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::ImportListBulkResource < Radarr::Model
  @[JSON::Field(key: "ids")]
  property ids = [] of Int32

  @[JSON::Field(key: "tags")]
  property tags = [] of Int32

  @[JSON::Field(key: "applyTags")]
  property apply_tags : Radarr::ApplyTags?

  @[JSON::Field(key: "enabled")]
  property enabled : Bool?

  @[JSON::Field(key: "enableAuto")]
  property enable_auto : Bool?

  @[JSON::Field(key: "rootFolderPath")]
  property root_folder_path : String?

  @[JSON::Field(key: "qualityProfileId")]
  property quality_profile_id : Int32?

  @[JSON::Field(key: "minimumAvailability")]
  property minimum_availability : Radarr::MovieStatusType?
end
