# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::IndexerConfigResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "minimumAge")]
  property minimum_age : Int32?

  @[JSON::Field(key: "maximumSize")]
  property maximum_size : Int32?

  @[JSON::Field(key: "retention")]
  property retention : Int32?

  @[JSON::Field(key: "rssSyncInterval")]
  property rss_sync_interval : Int32?

  @[JSON::Field(key: "preferIndexerFlags")]
  property prefer_indexer_flags : Bool?

  @[JSON::Field(key: "availabilityDelay")]
  property availability_delay : Int32?

  @[JSON::Field(key: "allowHardcodedSubs")]
  property allow_hardcoded_subs : Bool?

  @[JSON::Field(key: "whitelistedHardcodedSubs")]
  property whitelisted_hardcoded_subs : String?
end
