# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::IndexerResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "fields")]
  property fields = [] of Radarr::Model::Field

  @[JSON::Field(key: "implementationName")]
  property implementation_name : String?

  @[JSON::Field(key: "implementation")]
  property implementation : String?

  @[JSON::Field(key: "configContract")]
  property config_contract : String?

  @[JSON::Field(key: "infoLink")]
  property info_link : String?

  @[JSON::Field(key: "message")]
  property message : Radarr::Model::ProviderMessage?

  @[JSON::Field(key: "tags")]
  property tags = [] of Int32

  @[JSON::Field(key: "presets")]
  property presets = [] of Radarr::Model::IndexerResource

  @[JSON::Field(key: "enableRss")]
  property enable_rss : Bool?

  @[JSON::Field(key: "enableAutomaticSearch")]
  property enable_automatic_search : Bool?

  @[JSON::Field(key: "enableInteractiveSearch")]
  property enable_interactive_search : Bool?

  @[JSON::Field(key: "supportsRss")]
  property supports_rss : Bool?

  @[JSON::Field(key: "supportsSearch")]
  property supports_search : Bool?

  @[JSON::Field(key: "protocol")]
  property protocol : Radarr::DownloadProtocol?

  @[JSON::Field(key: "priority")]
  property priority : Int32?

  @[JSON::Field(key: "downloadClientId")]
  property download_client_id : Int32?
end
