# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::LocalizationLanguageResource < Radarr::Model
  @[JSON::Field(key: "identifier")]
  property identifier : String?
end
