# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::ManualImportReprocessResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "path")]
  property path : String?

  @[JSON::Field(key: "movieId")]
  property movie_id : Int32?

  @[JSON::Field(key: "movie")]
  property movie : Radarr::Model::MovieResource?

  @[JSON::Field(key: "quality")]
  property quality : Radarr::Model::QualityModel?

  @[JSON::Field(key: "languages")]
  property languages = [] of Radarr::Model::Language

  @[JSON::Field(key: "releaseGroup")]
  property release_group : String?

  @[JSON::Field(key: "downloadId")]
  property download_id : String?

  @[JSON::Field(key: "customFormats")]
  property custom_formats = [] of Radarr::Model::CustomFormatResource

  @[JSON::Field(key: "customFormatScore")]
  property custom_format_score : Int32?

  @[JSON::Field(key: "indexerFlags")]
  property indexer_flags : Int32?

  @[JSON::Field(key: "rejections")]
  property rejections = [] of Radarr::Model::ImportRejectionResource
end
