# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::MovieStatisticsResource < Radarr::Model
  @[JSON::Field(key: "movieFileCount")]
  property movie_file_count : Int32?

  @[JSON::Field(key: "sizeOnDisk")]
  property size_on_disk : Int64?

  @[JSON::Field(key: "releaseGroups")]
  property release_groups = [] of String
end
