# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::MovieResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "title")]
  property title : String?

  @[JSON::Field(key: "originalTitle")]
  property original_title : String?

  @[JSON::Field(key: "originalLanguage")]
  property original_language : Radarr::Model::Language?

  @[JSON::Field(key: "alternateTitles")]
  property alternate_titles = [] of Radarr::Model::AlternativeTitleResource

  @[JSON::Field(key: "secondaryYear")]
  property secondary_year : Int32?

  @[JSON::Field(key: "secondaryYearSourceId")]
  property secondary_year_source_id : Int32?

  @[JSON::Field(key: "sortTitle")]
  property sort_title : String?

  @[JSON::Field(key: "sizeOnDisk")]
  property size_on_disk : Int64?

  @[JSON::Field(key: "status")]
  property status : Radarr::MovieStatusType?

  @[JSON::Field(key: "overview")]
  property overview : String?

  @[JSON::Field(key: "inCinemas", converter: Radarr::TimeConverter)]
  property in_cinemas : Time?

  @[JSON::Field(key: "physicalRelease", converter: Radarr::TimeConverter)]
  property physical_release : Time?

  @[JSON::Field(key: "digitalRelease", converter: Radarr::TimeConverter)]
  property digital_release : Time?

  @[JSON::Field(key: "releaseDate", converter: Radarr::TimeConverter)]
  property release_date : Time?

  @[JSON::Field(key: "physicalReleaseNote")]
  property physical_release_note : String?

  @[JSON::Field(key: "images")]
  property images = [] of Radarr::Model::MediaCover

  @[JSON::Field(key: "website")]
  property website : String?

  @[JSON::Field(key: "remotePoster")]
  property remote_poster : String?

  @[JSON::Field(key: "year")]
  property year : Int32?

  @[JSON::Field(key: "youTubeTrailerId")]
  property you_tube_trailer_id : String?

  @[JSON::Field(key: "studio")]
  property studio : String?

  @[JSON::Field(key: "path")]
  property path : String?

  @[JSON::Field(key: "qualityProfileId")]
  property quality_profile_id : Int32?

  @[JSON::Field(key: "hasFile")]
  property has_file : Bool?

  @[JSON::Field(key: "movieFileId")]
  property movie_file_id : Int32?

  @[JSON::Field(key: "monitored")]
  property monitored : Bool?

  @[JSON::Field(key: "minimumAvailability")]
  property minimum_availability : Radarr::MovieStatusType?

  @[JSON::Field(key: "isAvailable")]
  property is_available : Bool?

  @[JSON::Field(key: "folderName")]
  property folder_name : String?

  @[JSON::Field(key: "runtime")]
  property runtime : Int32?

  @[JSON::Field(key: "cleanTitle")]
  property clean_title : String?

  @[JSON::Field(key: "imdbId")]
  property imdb_id : String?

  @[JSON::Field(key: "tmdbId")]
  property tmdb_id : Int32?

  @[JSON::Field(key: "titleSlug")]
  property title_slug : String?

  @[JSON::Field(key: "rootFolderPath")]
  property root_folder_path : String?

  @[JSON::Field(key: "folder")]
  property folder : String?

  @[JSON::Field(key: "certification")]
  property certification : String?

  @[JSON::Field(key: "genres")]
  property genres = [] of String

  @[JSON::Field(key: "keywords")]
  property keywords = [] of String

  @[JSON::Field(key: "tags")]
  property tags = [] of Int32

  @[JSON::Field(key: "added", converter: Radarr::TimeConverter)]
  property added : Time?

  @[JSON::Field(key: "addOptions")]
  property add_options : Radarr::Model::AddMovieOptions?

  @[JSON::Field(key: "ratings")]
  property ratings : Radarr::Model::Ratings?

  @[JSON::Field(key: "movieFile")]
  property movie_file : Radarr::Model::MovieFileResource?

  @[JSON::Field(key: "collection")]
  property collection : Radarr::Model::MovieCollectionResource?

  @[JSON::Field(key: "popularity")]
  property popularity : Float64?

  @[JSON::Field(key: "lastSearchTime", converter: Radarr::TimeConverter)]
  property last_search_time : Time?

  @[JSON::Field(key: "statistics")]
  property statistics : Radarr::Model::MovieStatisticsResource?
end
