# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::MovieFileResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "movieId")]
  property movie_id : Int32?

  @[JSON::Field(key: "relativePath")]
  property relative_path : String?

  @[JSON::Field(key: "path")]
  property path : String?

  @[JSON::Field(key: "size")]
  property size : Int64?

  @[JSON::Field(key: "dateAdded", converter: Radarr::TimeConverter)]
  property date_added : Time?

  @[JSON::Field(key: "sceneName")]
  property scene_name : String?

  @[JSON::Field(key: "releaseGroup")]
  property release_group : String?

  @[JSON::Field(key: "edition")]
  property edition : String?

  @[JSON::Field(key: "languages")]
  property languages = [] of Radarr::Model::Language

  @[JSON::Field(key: "quality")]
  property quality : Radarr::Model::QualityModel?

  @[JSON::Field(key: "customFormats")]
  property custom_formats = [] of Radarr::Model::CustomFormatResource

  @[JSON::Field(key: "customFormatScore")]
  property custom_format_score : Int32?

  @[JSON::Field(key: "indexerFlags")]
  property indexer_flags : Int32?

  @[JSON::Field(key: "mediaInfo")]
  property media_info : Radarr::Model::MediaInfoResource?

  @[JSON::Field(key: "originalFilePath")]
  property original_file_path : String?

  @[JSON::Field(key: "qualityCutoffNotMet")]
  property quality_cutoff_not_met : Bool?
end
