# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::MovieEditorResource < Radarr::Model
  @[JSON::Field(key: "movieIds")]
  property movie_ids = [] of Int32

  @[JSON::Field(key: "monitored")]
  property monitored : Bool?

  @[JSON::Field(key: "qualityProfileId")]
  property quality_profile_id : Int32?

  @[JSON::Field(key: "minimumAvailability")]
  property minimum_availability : Radarr::MovieStatusType?

  @[JSON::Field(key: "rootFolderPath")]
  property root_folder_path : String?

  @[JSON::Field(key: "tags")]
  property tags = [] of Int32

  @[JSON::Field(key: "applyTags")]
  property apply_tags : Radarr::ApplyTags?

  @[JSON::Field(key: "moveFiles")]
  property move_files : Bool?

  @[JSON::Field(key: "deleteFiles")]
  property delete_files : Bool?

  @[JSON::Field(key: "addImportExclusion")]
  property add_import_exclusion : Bool?
end
