# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::MovieFileListResource < Radarr::Model
  @[JSON::Field(key: "movieFileIds")]
  property movie_file_ids = [] of Int32

  @[JSON::Field(key: "languages")]
  property languages = [] of Radarr::Model::Language

  @[JSON::Field(key: "quality")]
  property quality : Radarr::Model::QualityModel?

  @[JSON::Field(key: "edition")]
  property edition : String?

  @[JSON::Field(key: "releaseGroup")]
  property release_group : String?

  @[JSON::Field(key: "sceneName")]
  property scene_name : String?

  @[JSON::Field(key: "indexerFlags")]
  property indexer_flags : Int32?
end
