# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::MovieCollectionResource < Radarr::Model
  @[JSON::Field(key: "title")]
  property title : String?

  @[JSON::Field(key: "tmdbId")]
  property tmdb_id : Int32?
end
