# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::NamingConfigResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "renameMovies")]
  property rename_movies : Bool?

  @[JSON::Field(key: "replaceIllegalCharacters")]
  property replace_illegal_characters : Bool?

  @[JSON::Field(key: "colonReplacementFormat")]
  property colon_replacement_format : Radarr::ColonReplacementFormat?

  @[JSON::Field(key: "standardMovieFormat")]
  property standard_movie_format : String?

  @[JSON::Field(key: "movieFolderFormat")]
  property movie_folder_format : String?
end
