# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::NotificationResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "fields")]
  property fields = [] of Radarr::Model::Field

  @[JSON::Field(key: "implementationName")]
  property implementation_name : String?

  @[JSON::Field(key: "implementation")]
  property implementation : String?

  @[JSON::Field(key: "configContract")]
  property config_contract : String?

  @[JSON::Field(key: "infoLink")]
  property info_link : String?

  @[JSON::Field(key: "message")]
  property message : Radarr::Model::ProviderMessage?

  @[JSON::Field(key: "tags")]
  property tags = [] of Int32

  @[JSON::Field(key: "presets")]
  property presets = [] of Radarr::Model::NotificationResource

  @[JSON::Field(key: "link")]
  property link : String?

  @[JSON::Field(key: "onGrab")]
  property on_grab : Bool?

  @[JSON::Field(key: "onDownload")]
  property on_download : Bool?

  @[JSON::Field(key: "onUpgrade")]
  property on_upgrade : Bool?

  @[JSON::Field(key: "onRename")]
  property on_rename : Bool?

  @[JSON::Field(key: "onMovieAdded")]
  property on_movie_added : Bool?

  @[JSON::Field(key: "onMovieDelete")]
  property on_movie_delete : Bool?

  @[JSON::Field(key: "onMovieFileDelete")]
  property on_movie_file_delete : Bool?

  @[JSON::Field(key: "onMovieFileDeleteForUpgrade")]
  property on_movie_file_delete_for_upgrade : Bool?

  @[JSON::Field(key: "onHealthIssue")]
  property on_health_issue : Bool?

  @[JSON::Field(key: "includeHealthWarnings")]
  property include_health_warnings : Bool?

  @[JSON::Field(key: "onHealthRestored")]
  property on_health_restored : Bool?

  @[JSON::Field(key: "onApplicationUpdate")]
  property on_application_update : Bool?

  @[JSON::Field(key: "onManualInteractionRequired")]
  property on_manual_interaction_required : Bool?

  @[JSON::Field(key: "supportsOnGrab")]
  property supports_on_grab : Bool?

  @[JSON::Field(key: "supportsOnDownload")]
  property supports_on_download : Bool?

  @[JSON::Field(key: "supportsOnUpgrade")]
  property supports_on_upgrade : Bool?

  @[JSON::Field(key: "supportsOnRename")]
  property supports_on_rename : Bool?

  @[JSON::Field(key: "supportsOnMovieAdded")]
  property supports_on_movie_added : Bool?

  @[JSON::Field(key: "supportsOnMovieDelete")]
  property supports_on_movie_delete : Bool?

  @[JSON::Field(key: "supportsOnMovieFileDelete")]
  property supports_on_movie_file_delete : Bool?

  @[JSON::Field(key: "supportsOnMovieFileDeleteForUpgrade")]
  property supports_on_movie_file_delete_for_upgrade : Bool?

  @[JSON::Field(key: "supportsOnHealthIssue")]
  property supports_on_health_issue : Bool?

  @[JSON::Field(key: "supportsOnHealthRestored")]
  property supports_on_health_restored : Bool?

  @[JSON::Field(key: "supportsOnApplicationUpdate")]
  property supports_on_application_update : Bool?

  @[JSON::Field(key: "supportsOnManualInteractionRequired")]
  property supports_on_manual_interaction_required : Bool?

  @[JSON::Field(key: "testCommand")]
  property test_command : String?
end
