# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::ParsedMovieInfo < Radarr::Model
  @[JSON::Field(key: "movieTitles")]
  property movie_titles = [] of String

  @[JSON::Field(key: "originalTitle")]
  property original_title : String?

  @[JSON::Field(key: "releaseTitle")]
  property release_title : String?

  @[JSON::Field(key: "simpleReleaseTitle")]
  property simple_release_title : String?

  @[JSON::Field(key: "quality")]
  property quality : Radarr::Model::QualityModel?

  @[JSON::Field(key: "languages")]
  property languages = [] of Radarr::Model::Language

  @[JSON::Field(key: "releaseGroup")]
  property release_group : String?

  @[JSON::Field(key: "releaseHash")]
  property release_hash : String?

  @[JSON::Field(key: "edition")]
  property edition : String?

  @[JSON::Field(key: "year")]
  property year : Int32?

  @[JSON::Field(key: "imdbId")]
  property imdb_id : String?

  @[JSON::Field(key: "tmdbId")]
  property tmdb_id : Int32?

  @[JSON::Field(key: "hardcodedSubs")]
  property hardcoded_subs : String?

  @[JSON::Field(key: "movieTitle")]
  property movie_title : String?

  @[JSON::Field(key: "primaryMovieTitle")]
  property primary_movie_title : String?
end
