# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::ParseResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "title")]
  property title : String?

  @[JSON::Field(key: "parsedMovieInfo")]
  property parsed_movie_info : Radarr::Model::ParsedMovieInfo?

  @[JSON::Field(key: "movie")]
  property movie : Radarr::Model::MovieResource?

  @[JSON::Field(key: "languages")]
  property languages = [] of Radarr::Model::Language

  @[JSON::Field(key: "customFormats")]
  property custom_formats = [] of Radarr::Model::CustomFormatResource

  @[JSON::Field(key: "customFormatScore")]
  property custom_format_score : Int32?
end
