# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::PingResource < Radarr::Model
  @[JSON::Field(key: "status")]
  property status : String?
end
