# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::ProviderMessage < Radarr::Model
  @[JSON::Field(key: "message")]
  property message : String?

  @[JSON::Field(key: "type")]
  property type_field : Radarr::ProviderMessageType?
end
