# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::QualityDefinitionLimitsResource < Radarr::Model
  @[JSON::Field(key: "min")]
  property min : Int32?

  @[JSON::Field(key: "max")]
  property max : Int32?
end
