# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::QualityProfileQualityItemResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "quality")]
  property quality : Radarr::Model::Quality?

  @[JSON::Field(key: "items")]
  property items = [] of Radarr::Model::QualityProfileQualityItemResource

  @[JSON::Field(key: "allowed")]
  property allowed : Bool?
end
