# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::Quality < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "source")]
  property source : Radarr::QualitySource?

  @[JSON::Field(key: "resolution")]
  property resolution : Int32?

  @[JSON::Field(key: "modifier")]
  property modifier : Radarr::Modifier?
end
