# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::QualityModel < Radarr::Model
  @[JSON::Field(key: "quality")]
  property quality : Radarr::Model::Quality?

  @[JSON::Field(key: "revision")]
  property revision : Radarr::Model::Revision?
end
