# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::QualityProfileResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "upgradeAllowed")]
  property upgrade_allowed : Bool?

  @[JSON::Field(key: "cutoff")]
  property cutoff : Int32?

  @[JSON::Field(key: "items")]
  property items = [] of Radarr::Model::QualityProfileQualityItemResource

  @[JSON::Field(key: "minFormatScore")]
  property min_format_score : Int32?

  @[JSON::Field(key: "cutoffFormatScore")]
  property cutoff_format_score : Int32?

  @[JSON::Field(key: "minUpgradeFormatScore")]
  property min_upgrade_format_score : Int32?

  @[JSON::Field(key: "formatItems")]
  property format_items = [] of Radarr::Model::ProfileFormatItemResource

  @[JSON::Field(key: "language")]
  property language : Radarr::Model::Language?
end
