# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::QueueResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "movieId")]
  property movie_id : Int32?

  @[JSON::Field(key: "movie")]
  property movie : Radarr::Model::MovieResource?

  @[JSON::Field(key: "languages")]
  property languages = [] of Radarr::Model::Language

  @[JSON::Field(key: "quality")]
  property quality : Radarr::Model::QualityModel?

  @[JSON::Field(key: "customFormats")]
  property custom_formats = [] of Radarr::Model::CustomFormatResource

  @[JSON::Field(key: "customFormatScore")]
  property custom_format_score : Int32?

  @[JSON::Field(key: "size")]
  property size : Float64?

  @[JSON::Field(key: "title")]
  property title : String?

  @[JSON::Field(key: "estimatedCompletionTime", converter: Radarr::TimeConverter)]
  property estimated_completion_time : Time?

  @[JSON::Field(key: "added", converter: Radarr::TimeConverter)]
  property added : Time?

  @[JSON::Field(key: "status")]
  property status : Radarr::QueueStatus?

  @[JSON::Field(key: "trackedDownloadStatus")]
  property tracked_download_status : Radarr::TrackedDownloadStatus?

  @[JSON::Field(key: "trackedDownloadState")]
  property tracked_download_state : Radarr::TrackedDownloadState?

  @[JSON::Field(key: "statusMessages")]
  property status_messages = [] of Radarr::Model::TrackedDownloadStatusMessage

  @[JSON::Field(key: "errorMessage")]
  property error_message : String?

  @[JSON::Field(key: "downloadId")]
  property download_id : String?

  @[JSON::Field(key: "protocol")]
  property protocol : Radarr::DownloadProtocol?

  @[JSON::Field(key: "downloadClient")]
  property download_client : String?

  @[JSON::Field(key: "downloadClientHasPostImportCategory")]
  property download_client_has_post_import_category : Bool?

  @[JSON::Field(key: "indexer")]
  property indexer : String?

  @[JSON::Field(key: "outputPath")]
  property output_path : String?

  @[JSON::Field(key: "sizeleft")]
  property sizeleft : Float64?

  @[JSON::Field(key: "timeleft")]
  property timeleft : String?
end
