# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::QueueResourcePagingResource < Radarr::Model
  @[JSON::Field(key: "page")]
  property page : Int32?

  @[JSON::Field(key: "pageSize")]
  property page_size : Int32?

  @[JSON::Field(key: "sortKey")]
  property sort_key : String?

  @[JSON::Field(key: "sortDirection")]
  property sort_direction : Radarr::SortDirection?

  @[JSON::Field(key: "totalRecords")]
  property total_records : Int32?

  @[JSON::Field(key: "records")]
  property records = [] of Radarr::Model::QueueResource
end
