# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::RatingChild < Radarr::Model
  @[JSON::Field(key: "votes")]
  property votes : Int32?

  @[JSON::Field(key: "value")]
  property value : Float64?

  @[JSON::Field(key: "type")]
  property type_field : Radarr::RatingType?
end
