# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::Ratings < Radarr::Model
  @[JSON::Field(key: "imdb")]
  property imdb : Radarr::Model::RatingChild?

  @[JSON::Field(key: "tmdb")]
  property tmdb : Radarr::Model::RatingChild?

  @[JSON::Field(key: "metacritic")]
  property metacritic : Radarr::Model::RatingChild?

  @[JSON::Field(key: "rottenTomatoes")]
  property rotten_tomatoes : Radarr::Model::RatingChild?

  @[JSON::Field(key: "trakt")]
  property trakt : Radarr::Model::RatingChild?
end
