# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::ReleaseResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "guid")]
  property guid : String?

  @[JSON::Field(key: "quality")]
  property quality : Radarr::Model::QualityModel?

  @[JSON::Field(key: "customFormats")]
  property custom_formats = [] of Radarr::Model::CustomFormatResource

  @[JSON::Field(key: "customFormatScore")]
  property custom_format_score : Int32?

  @[JSON::Field(key: "qualityWeight")]
  property quality_weight : Int32?

  @[JSON::Field(key: "age")]
  property age : Int32?

  @[JSON::Field(key: "ageHours")]
  property age_hours : Float64?

  @[JSON::Field(key: "ageMinutes")]
  property age_minutes : Float64?

  @[JSON::Field(key: "size")]
  property size : Int64?

  @[JSON::Field(key: "indexerId")]
  property indexer_id : Int32?

  @[JSON::Field(key: "indexer")]
  property indexer : String?

  @[JSON::Field(key: "releaseGroup")]
  property release_group : String?

  @[JSON::Field(key: "subGroup")]
  property sub_group : String?

  @[JSON::Field(key: "releaseHash")]
  property release_hash : String?

  @[JSON::Field(key: "title")]
  property title : String?

  @[JSON::Field(key: "sceneSource")]
  property scene_source : Bool?

  @[JSON::Field(key: "movieTitles")]
  property movie_titles = [] of String

  @[JSON::Field(key: "languages")]
  property languages = [] of Radarr::Model::Language

  @[JSON::Field(key: "mappedMovieId")]
  property mapped_movie_id : Int32?

  @[JSON::Field(key: "approved")]
  property approved : Bool?

  @[JSON::Field(key: "temporarilyRejected")]
  property temporarily_rejected : Bool?

  @[JSON::Field(key: "rejected")]
  property rejected : Bool?

  @[JSON::Field(key: "tmdbId")]
  property tmdb_id : Int32?

  @[JSON::Field(key: "imdbId")]
  property imdb_id : Int32?

  @[JSON::Field(key: "rejections")]
  property rejections = [] of String

  @[JSON::Field(key: "publishDate", converter: Radarr::TimeConverter)]
  property publish_date : Time?

  @[JSON::Field(key: "commentUrl")]
  property comment_url : String?

  @[JSON::Field(key: "downloadUrl")]
  property download_url : String?

  @[JSON::Field(key: "infoUrl")]
  property info_url : String?

  @[JSON::Field(key: "movieRequested")]
  property movie_requested : Bool?

  @[JSON::Field(key: "downloadAllowed")]
  property download_allowed : Bool?

  @[JSON::Field(key: "releaseWeight")]
  property release_weight : Int32?

  @[JSON::Field(key: "edition")]
  property edition : String?

  @[JSON::Field(key: "magnetUrl")]
  property magnet_url : String?

  @[JSON::Field(key: "infoHash")]
  property info_hash : String?

  @[JSON::Field(key: "seeders")]
  property seeders : Int32?

  @[JSON::Field(key: "leechers")]
  property leechers : Int32?

  @[JSON::Field(key: "protocol")]
  property protocol : Radarr::DownloadProtocol?

  @[JSON::Field(key: "indexerFlags")]
  property indexer_flags : JSON::Any?

  @[JSON::Field(key: "movieId")]
  property movie_id : Int32?

  @[JSON::Field(key: "downloadClientId")]
  property download_client_id : Int32?

  @[JSON::Field(key: "downloadClient")]
  property download_client : String?

  @[JSON::Field(key: "shouldOverride")]
  property should_override : Bool?
end
