# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::RenameMovieResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "movieId")]
  property movie_id : Int32?

  @[JSON::Field(key: "movieFileId")]
  property movie_file_id : Int32?

  @[JSON::Field(key: "existingPath")]
  property existing_path : String?

  @[JSON::Field(key: "newPath")]
  property new_path : String?
end
