# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::Revision < Radarr::Model
  @[JSON::Field(key: "version")]
  property version : Int32?

  @[JSON::Field(key: "real")]
  property real : Int32?

  @[JSON::Field(key: "isRepack")]
  property is_repack : Bool?
end
