# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::RootFolderResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "path")]
  property path : String?

  @[JSON::Field(key: "accessible")]
  property accessible : Bool?

  @[JSON::Field(key: "freeSpace")]
  property free_space : Int64?

  @[JSON::Field(key: "unmappedFolders")]
  property unmapped_folders = [] of Radarr::Model::UnmappedFolder
end
