# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::SelectOption < Radarr::Model
  @[JSON::Field(key: "value")]
  property value : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "order")]
  property order : Int32?

  @[JSON::Field(key: "hint")]
  property hint : String?

  @[JSON::Field(key: "dividerAfter")]
  property divider_after : Bool?
end
