# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::TaskResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "taskName")]
  property task_name : String?

  @[JSON::Field(key: "interval")]
  property interval : Int32?

  @[JSON::Field(key: "lastExecution", converter: Radarr::TimeConverter)]
  property last_execution : Time?

  @[JSON::Field(key: "lastStartTime", converter: Radarr::TimeConverter)]
  property last_start_time : Time?

  @[JSON::Field(key: "nextExecution", converter: Radarr::TimeConverter)]
  property next_execution : Time?

  @[JSON::Field(key: "lastDuration")]
  property last_duration : String?
end
