# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::UiConfigResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "firstDayOfWeek")]
  property first_day_of_week : Int32?

  @[JSON::Field(key: "calendarWeekColumnHeader")]
  property calendar_week_column_header : String?

  @[JSON::Field(key: "movieRuntimeFormat")]
  property movie_runtime_format : Radarr::MovieRuntimeFormatType?

  @[JSON::Field(key: "shortDateFormat")]
  property short_date_format : String?

  @[JSON::Field(key: "longDateFormat")]
  property long_date_format : String?

  @[JSON::Field(key: "timeFormat")]
  property time_format : String?

  @[JSON::Field(key: "showRelativeDates")]
  property show_relative_dates : Bool?

  @[JSON::Field(key: "enableColorImpairedMode")]
  property enable_color_impaired_mode : Bool?

  @[JSON::Field(key: "movieInfoLanguage")]
  property movie_info_language : Int32?

  @[JSON::Field(key: "uiLanguage")]
  property ui_language : Int32?

  @[JSON::Field(key: "theme")]
  property theme : String?
end
