# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::UnmappedFolder < Radarr::Model
  @[JSON::Field(key: "name")]
  property name : String?

  @[JSON::Field(key: "path")]
  property path : String?

  @[JSON::Field(key: "relativePath")]
  property relative_path : String?
end
