# AUTO-GENERATED by tools/generate.cr — DO NOT EDIT.
# Regenerate via: crystal run tools/generate.cr

class Radarr::Model::UpdateResource < Radarr::Model
  @[JSON::Field(key: "id")]
  property id : Int32?

  @[JSON::Field(key: "version")]
  property version : String?

  @[JSON::Field(key: "branch")]
  property branch : String?

  @[JSON::Field(key: "releaseDate", converter: Radarr::TimeConverter)]
  property release_date : Time?

  @[JSON::Field(key: "fileName")]
  property file_name : String?

  @[JSON::Field(key: "url")]
  property url : String?

  @[JSON::Field(key: "installed")]
  property installed : Bool?

  @[JSON::Field(key: "installedOn", converter: Radarr::TimeConverter)]
  property installed_on : Time?

  @[JSON::Field(key: "installable")]
  property installable : Bool?

  @[JSON::Field(key: "latest")]
  property latest : Bool?

  @[JSON::Field(key: "changes")]
  property changes : Radarr::Model::UpdateChanges?

  @[JSON::Field(key: "hash")]
  property hash : String?
end
